### ISSUE TITLE
Does this already automatically install homebrew?

### ISSUE THREAD

**Issue by danielfalbo** [d12frosted/dotbot-brew#16]
I'm not sure, does this already automatically install homebrew if it is not already installed in the machine when bootstrapping the dotfiles? Otherwise it would be a great thing, wouldn't it?

**Comment by d12frosted** [comment]
It does [bootstrap][1] itself.

  [1]: https://github.com/d12frosted/dotbot-brew/blob/master/brew.py#L91

**Comment by danielfalbo** [comment]
Thank you! I'm playing a little bit with my dotfiles and I wasn't sure about this : )
