### ISSUE TITLE
Clean install fails at cask items

### ISSUE THREAD

**Issue by Thinkscape** [d12frosted/dotbot-brew#17]
Here's what happens on a brand new OSX installation:
```
Installing from file install.conf/Brewfile
Updating Homebrew...
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 5331 (delta 13), reused 18 (delta 6), pack-reused 5299
Receiving objects: 100% (5331/5331), 1.20 MiB | 1.16 MiB/s, done.
Resolving deltas: 100% (3117/3117), done.
Tapped 1 command (104 files, 1.5MB).
Error: Cask 'workflowy' is unavailable: No Cask with this name exists.
Installing workflowy has failed!
Error: Cask 'google-chrome' is unavailable: No Cask with this name exists.
Installing google-chrome has failed!
Error: Cask 'firefox' is unavailable: No Cask with this name exists.
```

It seems that the cask has not initialised yet when dotbot-brew is trying to install casks.
Running any cask command manually in terminal will trigger the init process, like so:
```
brew cask info 
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 4, done.
...
```

It's probably an easy fix. What do you think?

**Comment by d12frosted** [comment]
Hey, should be fixed by https://github.com/d12frosted/dotbot-brew/commit/fc036f8692daa1a3e0861f08e4abff6c58dc7f2a. I don't have a machine I can test it on. AFAIK GitHub machines come with cask pre-bootstrapped. Would be lovely if you could test it.

**Comment by danielfalbo** [comment]
After the latest brew updates, it's also possible to install casks as following fwiw.

![Screenshot 2020-12-21 at 14 15 48](https://user-images.githubusercontent.com/39460524/102781042-4c0d6100-4397-11eb-8dab-79f3f934004f.png)
