### ISSUE TITLE
Support Brewfile

### ISSUE THREAD

**Issue by sobolevn** [d12frosted/dotbot-brew#7]
Right now there's a cool feature: https://github.com/Homebrew/homebrew-bundle

It allows to use `Brewfile` like this: `brew bundle dump`
And to install: `brew bundle`

Here's an example: https://github.com/sobolevn/dotfiles/blob/master/Brewfile

It would be nice to support this format. Like this:

```yaml
 - brewfile: 
     "path/to/Brewfile"
```

**Comment by d12frosted** [comment]
Sounds very interesting and solves several feature requests in this repository. I'll take a look. Hope to do it soon 😸

**Comment by sobolevn** [comment]
Just for the reference, I have implemented this feature in a new plugin: https://github.com/sobolevn/dotbot-brewfile

Could you please make a reference to it from your `README`?
Thanks! I would appreciate any feedback.

**Comment by d12frosted** [comment]
@sobolevn 

That's nice! Thanks for sharing it. I'll take a look at it ✨

**Comment by d12frosted** [comment]
Thanks to @CaptnBlubber we now have support for brewfile.
